version: "3"

services:
  nginx:
    image: nginx:alpine
    container_name: my-nginx
    hostname: nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./nginx/ssl/:/etc/nginx/ssl/:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./log/nginx/:/var/log/nginx/:rw
    networks:
      - net-v2ray
      - net-node
    environment:
        - NODESERVER=node
        - NODEPORT=30003
        - V2RAYSERVER=v2ray
        - V2RAYPORT=50001
  v2ray:
      image: v2ray/official
      container_name: my-v2ray
      hostname: v2ray
      expose:
        - "50001"
      ports:
        - "50001:50001"
      restart: always
      volumes:
        - ./v2ray/config.json:/etc/v2ray/config.json:ro
        - ./log/v2ray/:/var/log/v2ray/:rw
      networks:
        - net-v2ray
        - net-node
  node:
    build: .
    container_name: my-node
    hostname: node
    expose:
      - "30003"
    volumes:
      - ./:/chatgpt/
    ports:
      - "30003:30003"
    restart: always
    networks:
          - net-node
networks:
  net-node:
  net-v2ray: